// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uqjyoqkejbwrcyroruku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxanlvcWtlamJ3cmN5cm9ydWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Njk4MjQsImV4cCI6MjA2ODI0NTgyNH0.4EGGBzSV2jYIJOPO5D1fvBN2Mv-lcZzHihRTmtKjNCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);