// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uqjyoqkejbwrcyroruku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxanlvcWtlamJ3cmN5cm9ydWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Njk4MjQsImV4cCI6MjA2ODI0NTgyNH0.4EGGBzSV2jYIJOPO5D1fvBN2Mv-lcZzHihRTmtKjNCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== 'undefined';
const isDevHost = isBrowser && /^(localhost|127\.0\.0\.1)$/.test(window.location.hostname);

const proxiedFetch: typeof fetch = (input: RequestInfo | URL, init?: RequestInit) => {
  const asString = typeof input === 'string' ? input : (input as URL).toString();
  const rewritten = asString.startsWith(SUPABASE_URL)
    ? asString.replace(SUPABASE_URL, '/sb')
    : asString;
  return fetch(rewritten, init);
};

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: isDevHost ? proxiedFetch : fetch,
  },
});